### ISSUE TITLE
Blocks not properly styled on font size change

### ISSUE THREAD

**Issue by rcpacheco** [maenu/BlockStyler#4]
I had to change the font size of my Pharo and then the blocks could not be properly styled.

**Comment by maenu** [comment]
I cannot reproduce this issue. When I change the default font size and use force all, then reopen Nautilus or Calypso, blocks are styled just fine.

![image](https://user-images.githubusercontent.com/448312/31056032-ebb569f8-a6cb-11e7-8fd7-49cca9867146.png)

Can you give some more detailed steps to reproduce?

**Comment by rcpacheco** [comment]
Innitially everything was working great with the plugin. The problems started when I changed the font once. After that, I have not been able to make the BlockStyler work OK again. I closed the image and reopen it again. Was getting some Freefont error messages. So I removed all pharo images & vm's from my windows10 machine, removed any Pharo folder from C:\ProgramData and  C:\Users\username\AppData\Roaming. Downloaded a new image. Installed BlockStyle from the Catalog and got the result you see with Nautilius. Then installed Calypso and got the same result, using now the default font size. Tried enable & disable the freefont use, but got the same result :'(
Would it help if I share the wole image+vm with you? Do you think that this may be a Pharo issue with windows? If so, shoud I report it in the Pharo user group? Thanks 
![blockstyleproblem](https://user-images.githubusercontent.com/845725/31058959-6695fd90-a6c2-11e7-9e52-078ace4b7cf4.png)

**Comment by maenu** [comment]
Ah, I see the problem: BlockStyler is an IconStyler, those don't work properly with "Format as you read", as they are applied on the unformatted source. I created an issue in Calypso for that: https://github.com/dionisiydk/Calypso/issues/98

**Comment by rcpacheco** [comment]
You are right!! I disabled Format as you read and now it work OK. Thanks a lot!!

**Comment by maenu** [comment]
I hope we can get Calypso/Nautilus fixed, because I really like "Format as you read" as well.
